# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...

    - name: Login ke Docker HUB
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB }}

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: adhithia21/container-api-server:${{ github.run_number }}

  deploy-container:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: deploye container image
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_HUB }}
            docker pull adhithia21/container-api-server:${{ github.run_number }}
            docker rm -f api-server
            docker run --name api-server -d -p 80:8000 adhithia21/container-api-server:${{ github.run_number }}
